# This is a test template from zemit.toml, do not use it as a reference

[build]
optimize = "ReleaseSmall"
zig_args = ["-Dstrip=true"]

[release]
targets = [
    "x86_64-linux-gnu",
    # "x86_64-linux-musl",
    "aarch64-linux-gnu",
    # "aarch64-linux-musl",
    "arm-linux-gnueabihf",
    # "arm-linux-musleabihf",
    "riscv64-linux-gnu",
    # "riscv64-linux-musl",
    "x86_64-windows-gnu",
    # "x86_64-windows-msvc",
    "x86_64-macos",
    # "aarch64-macos",
]


#
[dist]
dir = "zemit/dist"
layout = "flat"
name_template = "{bin}-{version}-{target}{ext}"

[checksums]
enabled = true
algorithms = ["sha256"]
file = "checksums.txt"
